//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetTrack.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BetTrack.Resources.Languages.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        internal static string BtnClose {
            get {
                return ResourceManager.GetString("BtnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar.
        /// </summary>
        internal static string BtnContinue {
            get {
                return ResourceManager.GetString("BtnContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comenzar.
        /// </summary>
        internal static string BtnGoToLogin {
            get {
                return ResourceManager.GetString("BtnGoToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        internal static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuérdame.
        /// </summary>
        internal static string ChkRememberMe {
            get {
                return ResourceManager.GetString("ChkRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espere un momento....
        /// </summary>
        internal static string LblActivityIndicator {
            get {
                return ResourceManager.GetString("LblActivityIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algo falló enviando la información, lamentamos las molestias..
        /// </summary>
        internal static string LblBadRequestServer {
            get {
                return ResourceManager.GetString("LblBadRequestServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Registrate!.
        /// </summary>
        internal static string LblCreateNewAccount {
            get {
                return ResourceManager.GetString("LblCreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso importante.
        /// </summary>
        internal static string LblDialogTitle {
            get {
                return ResourceManager.GetString("LblDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Olvidaste tu contraseña?.
        /// </summary>
        internal static string LblForgotPassword {
            get {
                return ResourceManager.GetString("LblForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos no son válidos, revisa e intenta nuevamente..
        /// </summary>
        internal static string LblIncorrectData {
            get {
                return ResourceManager.GetString("LblIncorrectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captura el email asociado a tu cuenta y te enviaremos un email con las instrucciones para recuperar tu contraseña..
        /// </summary>
        internal static string LblInstructionsForgotPassword {
            get {
                return ResourceManager.GetString("LblInstructionsForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Aún no tienes una cuenta?.
        /// </summary>
        internal static string LblNewAccount {
            get {
                return ResourceManager.GetString("LblNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $action$ tipster.
        /// </summary>
        internal static string LblNewTipster {
            get {
                return ResourceManager.GetString("LblNewTipster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligatorio.
        /// </summary>
        internal static string LblRequired {
            get {
                return ResourceManager.GetString("LblRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string LblSave {
            get {
                return ResourceManager.GetString("LblSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hemos enviado un correo con instrucciones para poder restaurar tu contraseña..
        /// </summary>
        internal static string LblSendForgotPasswordInstructions {
            get {
                return ResourceManager.GetString("LblSendForgotPasswordInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro con éxito.
        /// </summary>
        internal static string LblSignUpSuccessful {
            get {
                return ResourceManager.GetString("LblSignUpSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te registraste con éxito, ahora puedes iniciar sesión en tu cuenta..
        /// </summary>
        internal static string LblSignUpSuccessfulMessage {
            get {
                return ResourceManager.GetString("LblSignUpSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saltar bienvenida.
        /// </summary>
        internal static string LblSkipWelcome {
            get {
                return ResourceManager.GetString("LblSkipWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del tipster.
        /// </summary>
        internal static string LblTipsterName {
            get {
                return ResourceManager.GetString("LblTipsterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        internal static string TxtEmail {
            get {
                return ResourceManager.GetString("TxtEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string TxtPassword {
            get {
                return ResourceManager.GetString("TxtPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        internal static string TxtUser {
            get {
                return ResourceManager.GetString("TxtUser", resourceCulture);
            }
        }
    }
}
