//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetTrack.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BetTrack.Resources.Languages.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        internal static string BtnClose {
            get {
                return ResourceManager.GetString("BtnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar.
        /// </summary>
        internal static string BtnContinue {
            get {
                return ResourceManager.GetString("BtnContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comenzar.
        /// </summary>
        internal static string BtnGoToLogin {
            get {
                return ResourceManager.GetString("BtnGoToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        internal static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sí.
        /// </summary>
        internal static string BtnYes {
            get {
                return ResourceManager.GetString("BtnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuérdame.
        /// </summary>
        internal static string ChkRememberMe {
            get {
                return ResourceManager.GetString("ChkRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espere un momento....
        /// </summary>
        internal static string LblActivityIndicator {
            get {
                return ResourceManager.GetString("LblActivityIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El importe de la apuesta es obligatorio..
        /// </summary>
        internal static string LblAmountBetRequired {
            get {
                return ResourceManager.GetString("LblAmountBetRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algo falló enviando la información, lamentamos las molestias..
        /// </summary>
        internal static string LblBadRequestServer {
            get {
                return ResourceManager.GetString("LblBadRequestServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $100.00.
        /// </summary>
        internal static string LblBankrollCapital {
            get {
                return ResourceManager.GetString("LblBankrollCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del bankroll.
        /// </summary>
        internal static string LblBankrollName {
            get {
                return ResourceManager.GetString("LblBankrollName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis bankrolls.
        /// </summary>
        internal static string LblBankrollsList {
            get {
                return ResourceManager.GetString("LblBankrollsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de bankroll.
        /// </summary>
        internal static string LblBankrollType {
            get {
                return ResourceManager.GetString("LblBankrollType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de la apuesta.
        /// </summary>
        internal static string LblBetDate {
            get {
                return ResourceManager.GetString("LblBetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de la apuesta es obligatorio..
        /// </summary>
        internal static string LblBetNameRequired {
            get {
                return ResourceManager.GetString("LblBetNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estatus de la apuesta es obligatorio..
        /// </summary>
        internal static string LblBetStatusRequired {
            get {
                return ResourceManager.GetString("LblBetStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Qué tipo de apuesta quieres?.
        /// </summary>
        internal static string LblBetType {
            get {
                return ResourceManager.GetString("LblBetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Día.
        /// </summary>
        internal static string LblCalendarDay {
            get {
                return ResourceManager.GetString("LblCalendarDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora.
        /// </summary>
        internal static string LblCalendarHour {
            get {
                return ResourceManager.GetString("LblCalendarHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minuto.
        /// </summary>
        internal static string LblCalendarMinute {
            get {
                return ResourceManager.GetString("LblCalendarMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes.
        /// </summary>
        internal static string LblCalendarMonth {
            get {
                return ResourceManager.GetString("LblCalendarMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Año.
        /// </summary>
        internal static string LblCalendarYear {
            get {
                return ResourceManager.GetString("LblCalendarYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cámara.
        /// </summary>
        internal static string LblCamera {
            get {
                return ResourceManager.GetString("LblCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona un casino para continuar..
        /// </summary>
        internal static string LblCasinoRequired {
            get {
                return ResourceManager.GetString("LblCasinoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorías.
        /// </summary>
        internal static string LblCategories {
            get {
                return ResourceManager.GetString("LblCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la categoría.
        /// </summary>
        internal static string LblCategoryName {
            get {
                return ResourceManager.GetString("LblCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de la categoría es obligatorio.
        /// </summary>
        internal static string LblCategoryNameRequired {
            get {
                return ResourceManager.GetString("LblCategoryNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona una categoría para continuar..
        /// </summary>
        internal static string LblCategoryRequired {
            get {
                return ResourceManager.GetString("LblCategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Que deseas realizar?.
        /// </summary>
        internal static string LblChooseAnAction {
            get {
                return ResourceManager.GetString("LblChooseAnAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elige una opción.
        /// </summary>
        internal static string LblChooseAnOption {
            get {
                return ResourceManager.GetString("LblChooseAnOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro de continuar con la eliminación?.
        /// </summary>
        internal static string LblConfirmDeleteCasinos {
            get {
                return ResourceManager.GetString("LblConfirmDeleteCasinos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Deseas eliminar al tipster $tipster$?.
        /// </summary>
        internal static string LblConfirmTipsterDelete {
            get {
                return ResourceManager.GetString("LblConfirmTipsterDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Registrate!.
        /// </summary>
        internal static string LblCreateNewAccount {
            get {
                return ResourceManager.GetString("LblCreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string LblDelete {
            get {
                return ResourceManager.GetString("LblDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro de eliminar la categoría $category$?.
        /// </summary>
        internal static string LblDeleteCategory {
            get {
                return ResourceManager.GetString("LblDeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso.
        /// </summary>
        internal static string LblDialogTitle {
            get {
                return ResourceManager.GetString("LblDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string LblEdit {
            get {
                return ResourceManager.GetString("LblEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aún no cuentas con tipsters registrados..
        /// </summary>
        internal static string LblEmptyTipsterList {
            get {
                return ResourceManager.GetString("LblEmptyTipsterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fue posible guardar los cambios, intente más tarde..
        /// </summary>
        internal static string LblFailed {
            get {
                return ResourceManager.GetString("LblFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Olvidaste tu contraseña?.
        /// </summary>
        internal static string LblForgotPassword {
            get {
                return ResourceManager.GetString("LblForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galería.
        /// </summary>
        internal static string LblGallery {
            get {
                return ResourceManager.GetString("LblGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importa tus casinos.
        /// </summary>
        internal static string LblImportCasino {
            get {
                return ResourceManager.GetString("LblImportCasino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos no son válidos, revisa e intenta nuevamente..
        /// </summary>
        internal static string LblIncorrectData {
            get {
                return ResourceManager.GetString("LblIncorrectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital inicial.
        /// </summary>
        internal static string LblInitialCapital {
            get {
                return ResourceManager.GetString("LblInitialCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captura el email asociado a tu cuenta y te enviaremos un email con las instrucciones para recuperar tu contraseña..
        /// </summary>
        internal static string LblInstructionsForgotPassword {
            get {
                return ResourceManager.GetString("LblInstructionsForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario o contraseña incorrectos..
        /// </summary>
        internal static string LblLoginMessageValidation {
            get {
                return ResourceManager.GetString("LblLoginMessageValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Aún no tienes una cuenta?.
        /// </summary>
        internal static string LblNewAccount {
            get {
                return ResourceManager.GetString("LblNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo bankroll.
        /// </summary>
        internal static string LblNewEditBankroll {
            get {
                return ResourceManager.GetString("LblNewEditBankroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $action$ categoría.
        /// </summary>
        internal static string LblNewEditCategory {
            get {
                return ResourceManager.GetString("LblNewEditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $action$ tipster.
        /// </summary>
        internal static string LblNewTipster {
            get {
                return ResourceManager.GetString("LblNewTipster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay casinos registrados.
        /// </summary>
        internal static string LblNoCasinos {
            get {
                return ResourceManager.GetString("LblNoCasinos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aún no tienes registradas categorías.
        /// </summary>
        internal static string LblNoCategories {
            get {
                return ResourceManager.GetString("LblNoCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron coincidencias.
        /// </summary>
        internal static string LblNoResults {
            get {
                return ResourceManager.GetString("LblNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El momio es obligatorio..
        /// </summary>
        internal static string LblOddRequired {
            get {
                return ResourceManager.GetString("LblOddRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parley.
        /// </summary>
        internal static string LblParleyBet {
            get {
                return ResourceManager.GetString("LblParleyBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capturar en %.
        /// </summary>
        internal static string LblPercentOption {
            get {
                return ResourceManager.GetString("LblPercentOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de cuota.
        /// </summary>
        internal static string LblQuotaFormatBankroll {
            get {
                return ResourceManager.GetString("LblQuotaFormatBankroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obligatorio.
        /// </summary>
        internal static string LblRequired {
            get {
                return ResourceManager.GetString("LblRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string LblSave {
            get {
                return ResourceManager.GetString("LblSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás buscando algo?.
        /// </summary>
        internal static string LblSearchPlaceholder {
            get {
                return ResourceManager.GetString("LblSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona el tipo de bankroll.
        /// </summary>
        internal static string LblSelectBankrollTypePlaceholder {
            get {
                return ResourceManager.GetString("LblSelectBankrollTypePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Que tipo de apuesta vas a registrar?.
        /// </summary>
        internal static string LblSelectBetType {
            get {
                return ResourceManager.GetString("LblSelectBetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona un casino.
        /// </summary>
        internal static string LblSelectCasino {
            get {
                return ResourceManager.GetString("LblSelectCasino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona una moneda.
        /// </summary>
        internal static string LblSelectCurrencyPlaceholder {
            get {
                return ResourceManager.GetString("LblSelectCurrencyPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona el formato de cuota.
        /// </summary>
        internal static string LblSelectQuotaFormatPlaceholder {
            get {
                return ResourceManager.GetString("LblSelectQuotaFormatPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hemos enviado un correo con instrucciones para poder restaurar tu contraseña..
        /// </summary>
        internal static string LblSendForgotPasswordInstructions {
            get {
                return ResourceManager.GetString("LblSendForgotPasswordInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La sesión caducó, inicia sesión nuevamente..
        /// </summary>
        internal static string LblSessionExpired {
            get {
                return ResourceManager.GetString("LblSessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro con éxito.
        /// </summary>
        internal static string LblSignUpSuccessful {
            get {
                return ResourceManager.GetString("LblSignUpSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te registraste con éxito, ahora puedes iniciar sesión en tu cuenta..
        /// </summary>
        internal static string LblSignUpSuccessfulMessage {
            get {
                return ResourceManager.GetString("LblSignUpSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derecha.
        /// </summary>
        internal static string LblSingleBet {
            get {
                return ResourceManager.GetString("LblSingleBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saltar bienvenida.
        /// </summary>
        internal static string LblSkipWelcome {
            get {
                return ResourceManager.GetString("LblSkipWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona un deporte para continuar..
        /// </summary>
        internal static string LblSportRequired {
            get {
                return ResourceManager.GetString("LblSportRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se guardaron los cambios con éxito..
        /// </summary>
        internal static string LblSuccess {
            get {
                return ResourceManager.GetString("LblSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del tipster.
        /// </summary>
        internal static string LblTipsterName {
            get {
                return ResourceManager.GetString("LblTipsterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del tipster es obligatorio..
        /// </summary>
        internal static string LblTipsterNameRequired {
            get {
                return ResourceManager.GetString("LblTipsterNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona un tipster para continuar..
        /// </summary>
        internal static string LblTipsterRequired {
            get {
                return ResourceManager.GetString("LblTipsterRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo es un campo obligatorio..
        /// </summary>
        internal static string LblUserEmailRequired {
            get {
                return ResourceManager.GetString("LblUserEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña es un campo obligatorio..
        /// </summary>
        internal static string LblUserPasswordRequired {
            get {
                return ResourceManager.GetString("LblUserPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        internal static string LblUserProfile {
            get {
                return ResourceManager.GetString("LblUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe.
        /// </summary>
        internal static string TxtBetAmount {
            get {
                return ResourceManager.GetString("TxtBetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe cobrado.
        /// </summary>
        internal static string TxtBetAmountCharged {
            get {
                return ResourceManager.GetString("TxtBetAmountCharged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago anticipado.
        /// </summary>
        internal static string TxtBetAP {
            get {
                return ResourceManager.GetString("TxtBetAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define tu apuesta.
        /// </summary>
        internal static string TxtBetBetTitle {
            get {
                return ResourceManager.GetString("TxtBetBetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importe retirado.
        /// </summary>
        internal static string TxtBetCashout {
            get {
                return ResourceManager.GetString("TxtBetCashout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona una categoría.
        /// </summary>
        internal static string TxtBetCategoryName {
            get {
                return ResourceManager.GetString("TxtBetCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        internal static string TxtBetDate {
            get {
                return ResourceManager.GetString("TxtBetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ganancias.
        /// </summary>
        internal static string TxtBetEarnings {
            get {
                return ResourceManager.GetString("TxtBetEarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apuesta gratuita.
        /// </summary>
        internal static string TxtBetFreeBet {
            get {
                return ResourceManager.GetString("TxtBetFreeBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apuesta en vivo.
        /// </summary>
        internal static string TxtBetLiveBet {
            get {
                return ResourceManager.GetString("TxtBetLiveBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string TxtBetName {
            get {
                return ResourceManager.GetString("TxtBetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Momio/Cuota.
        /// </summary>
        internal static string TxtBetOdds {
            get {
                return ResourceManager.GetString("TxtBetOdds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apuesta de pago.
        /// </summary>
        internal static string TxtBetPaidBet {
            get {
                return ResourceManager.GetString("TxtBetPaidBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona un deporte.
        /// </summary>
        internal static string TxtBetSportName {
            get {
                return ResourceManager.GetString("TxtBetSportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatus de la apuesta.
        /// </summary>
        internal static string TxtBetStatus {
            get {
                return ResourceManager.GetString("TxtBetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona un tipster.
        /// </summary>
        internal static string TxtBetTipsterName {
            get {
                return ResourceManager.GetString("TxtBetTipsterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de apuesta.
        /// </summary>
        internal static string TxtBetType {
            get {
                return ResourceManager.GetString("TxtBetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        internal static string TxtEmail {
            get {
                return ResourceManager.GetString("TxtEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string TxtName {
            get {
                return ResourceManager.GetString("TxtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        internal static string TxtNickname {
            get {
                return ResourceManager.GetString("TxtNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string TxtPassword {
            get {
                return ResourceManager.GetString("TxtPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string TxtThought {
            get {
                return ResourceManager.GetString("TxtThought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        internal static string TxtUser {
            get {
                return ResourceManager.GetString("TxtUser", resourceCulture);
            }
        }
    }
}
